---
title: "Training Program Schedule"
date: "2025-12-12"
date-modified: today
toc: false
---

## FISHERIES STOCK ASSESSMENT: CAPACITY-BUILDING TRAINING FOR SOMALIA'S MINISTRY OF FISHERIES AND BLUE ECONOMY STAFF

**Dar Es Salaam, United Republic of Tanzania**

### Day 1: Opening Ceremony & Module 1

**Date**: 13 December 2025\
**Venue**: White Sands Hotel

| Time | Activity | Facilitator(s) |
|----------------|----------------------------------------|----------------|
| 8:30 – 9:00 | Registration of the participants and other arrangements | Secretariat |
| 9:00– 9:10 | Round table introduction | Dr Rushingisha |
| 9:10 -9:20 | Remarks from TAFIRI Director General | Dr Rushingisha |
| 9:20 – 9:30 | Remarks from FAO Somalia Fisheries Team | Somali Coordinator |
| 9:30 -9:40 | Group photo | Herry KILELE |
| 09:40 – 10:20 | **Coffee/Tea Break** | All |
| 10:20 – 10:40 | Overview of the program | Dr Rushingisha George |
|  | **Module 1: Fundamentals of Fish stock assessment** |  |
| 10:40 – 11:20 | **Presentation 1**. Fundamentals and concepts | Dr Mathew & Dr. Mwakosya |
| 11:20 – 11:30 | Discussion | All |
| 11:30 – 12:10 | **Presentation 2**. Key biological and exploitation parameters | Dr Mathew & Dr. Mwakosya |
| 12:10 – 12:20 | Discussion | All |
| 12:30 -13:00 | **Presentation 3**. Population Dynamics | Dr. Mwakosya |
| 13:00 – 14:00 | **Lunch and Prayer** |  |
| 14:00 – 14:30 | **Presentation 4**: Data requirements | Dr Semba |
| 14:30 – 14:40 | Discussion | All |
| 14:40 – 15:20 | **Presentation 5**: Data collection methods | Eng. Innocent Sailale |
| 15:20 – 15:30 | Discussion | All |
| 15:30 – 16:00 | **Coffee Break** | All |
| 16:00– 16:30 | Closing and other arrangements | Dr Rushingisha |

### Day 2: Module 2 - Fisheries Data Types

**Date**: 14 December 2025\
**Venue**: White Sands Hotel

*Agenda to be added.*